name: OrderFlow CI Pipeline

on:
  push:
    branches: [ master, Develop ]
  pull_request:
    branches: [ master, Develop ]

jobs:
  build-and-test:
    name: Build and Run All Tests
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Source Code
      uses: actions/checkout@v4


    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x' 

    - name: Restore NuGet Packages
      run: dotnet restore OrderFlow.sln

    - name: Build Solution
      run: dotnet build OrderFlow.sln --configuration Release --no-restore

    - name: Run Core Unit Tests
      run: dotnet test Tests/OrderFlow.UnitTests/OrderFlow.UnitTests.csproj --configuration Release --no-build --verbosity normal

    - name: Run Payment Worker Tests
      run: dotnet test Tests/OrderFlow.Workers.Payment.Tests/OrderFlow.Worker.Payment.Tests.csproj --configuration Release --no-build --verbosity normal

    - name: Run Courier Worker Tests
      run: dotnet test Tests/OrderFlow.Worker.Courier.Tests/OrderFlow.Worker.Courier.Tests.csproj --configuration Release --no-build --verbosity normal

    - name: Run Integration Tests
      run: dotnet test Tests/OrderFlow.IntegrationTests/OrderFlow.IntegrationTests.csproj --configuration Release --no-build --verbosity normal